var BookList = {
data : (JSON.parse(`{
    "list":[
        {
            "name":"最强军火商",
            "urlname":"zqjhs"
        },
        {
            "name":"夜的命名术",
            "urlname":"ydmms"
        },
	    {
            "name":"斗罗2绝世唐门",
            "urlname":"dl2"
        },
	    {
            "name":"斗罗3龙王传说",
            "urlname":"dl3"
        },
	    {
            "name":"斗罗4终极斗罗",
            "urlname":"dl4"
        },
        {
            "name":"诡秘之主",
            "urlname":"gmzz"
        },
        {
            "name":"诡秘之主：午夜提灯",
            "urlname":"gmzz_wytd"
        },
        {
            "name":"全职高手",
            "urlname":"qzgs"
        },
        {
            "name":"学霸的黑科技系统",
            "urlname":"xbdhkjxt"
        },
        {
            "name":"吞噬星空",
            "urlname":"tsxk"
        },
        {
            "name":"冰火魔厨",
            "urlname":"bhmc"
        },
        {
            "name":"斗罗大陆外传神界传说",
            "urlname":"dldlwzsjcs"
        },
        {
            "name":"斗罗大陆外传史莱克天团",
            "urlname":"dldlwzslktt"
        },
        {
            "name":"唐门英雄传",
            "urlname":"tmyxz"
        },
        {
            "name":"欢迎来到实力至上主义的教室",
            "urlname":"slzsjs"
        },
		{
			"name":"牧龙师",
			"urlname":"mls"
		},
		{
			"name":"寄法",
			"urlname":"jf"
		},
		{
			"name":"全职法师",
			"urlname":"qzfs"
		},
		{
			"name":"仙武帝尊",
			"urlname":"xwdz"
		},
		{
			"name":"永恒之门",
			"urlname":"yhzm"
		},
		{
			"name":"游戏人生",
			"urlname":"nogamenolife"
		},
        {
            "name":"侦探已死",
            "urlname":"ztys/Text/contents.xhtml"
        },
        {
            "name":"马克思恩格斯全集",
            "urlname":"maen/maenquan.pdf"
        },
        {
            "name":"刀剑神域",
            "urlname":"djsy"
        },
        {
            "name":"旧约 魔法禁书目录",
            "urlname":"jymj"
        },
        {
            "name":"新约 魔法禁书目录",
            "urlname":"xymj"
        },
        {
            "name":"创约 魔法禁书目录",
            "urlname":"cymj"
        },
        {
            "name":"龙王的工作",
            "urlname":"lwdgz"
        },
        {
            "name":"恶魔高校",
            "urlname":"DXD"
        },
        {
            "name":"凡人修仙传",
            "urlname":"frxxz"
        }
    ]
}
`))
};